# Shell variables
# Generated by 'wal'
wallpaper='/home/ikkyuu/Pictures/wallpapers/1346801.jpeg'

# Special
background='#140f13'
foreground='#f2e6e1'
cursor='#f2e6e1'

# Colors
color0='#140f13'
color1='#C57446'
color2='#BA8A53'
color3='#D0A468'
color4='#6B7284'
color5='#86828A'
color6='#CCB39E'
color7='#f2e6e1'
color8='#a9a19d'
color9='#C57446'
color10='#BA8A53'
color11='#D0A468'
color12='#6B7284'
color13='#86828A'
color14='#CCB39E'
color15='#f2e6e1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
