#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/ikkyuu/Pictures/wallpapers/1346801.jpeg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
